# These are supported funding model platforms

github: jonaspammer
ko_fi: jonaspammer
liberapay: # Replace with a single Liberapay username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: jonaspammer
